# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e2288d8c8b26c508eaf25ef8f881aec905b69b52fc073780427be028c09cf4d9f41c45315300c9eb23ede8482a294ecfb1887a38847faf64517aab52819f568

test:
  secret_key_base: 21297b6129918a9f9f6a61f150a401622c2aa3ca848d2fcef6f4260dbf8f13a89a3587aab2d9e1fabba6f1c51aaa4942eae078adc751ca3e192e11103059e324

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
